name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build application
      run: dotnet build --configuration Release --no-restore

    - name: Run tests (if any)
      run: dotnet test --no-build --configuration Release --verbosity normal
      continue-on-error: true
      
    - name: Publish application
      run: |
        dotnet publish --configuration Release --self-contained true --runtime win-x64 -p:Version=${{ github.ref_name }} -p:AssemblyVersion=${{ github.ref_name }}.0 -p:FileVersion=${{ github.ref_name }}.0 -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -p:PublishSingleFile=true --output ./publish/win-x64
        dotnet publish --configuration Release -p:Version=${{ github.ref_name }} -p:AssemblyVersion=${{ github.ref_name }}.0 -p:FileVersion=${{ github.ref_name }}.0 --no-self-contained --output ./publish/portable 

        
    - name: Create release packages
      run: |
        # Create win-x64 standalone package
        cd publish/win-x64
        Compress-Archive -Path * -DestinationPath ../../BitTicker-win-x64-${{ github.ref_name }}.zip
        cd ../..
        
        # Create portable package
        cd publish/portable
        Compress-Archive -Path * -DestinationPath ../../BitTicker-portable-${{ github.ref_name }}.zip
        cd ../..
              
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: BitTicker ${{ github.ref_name }}
        body_path: CHANGELOG.md
        files: |
          BitTicker-win-x64-${{ github.ref_name }}.zip
          BitTicker-portable-${{ github.ref_name }}.zip
        draft: false
        prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'rc') }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BitTicker-builds
        path: |
          BitTicker-*.zip
