name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build application
      run: dotnet build --configuration Release --no-restore
      
    - name: Run tests (if any)
      run: dotnet test --no-build --configuration Release --verbosity normal
      continue-on-error: true
      
    - name: Publish application
      run: |
        dotnet publish --configuration Release --output ./publish/win-x64 --self-contained true --runtime win-x64 -p:PublishSingleFile=true
        dotnet publish --configuration Release --output ./publish/portable --no-self-contained
        
    - name: Create release packages
      run: |
        # Create win-x64 standalone package
        cd publish/win-x64
        Compress-Archive -Path * -DestinationPath ../../BitTicker-win-x64-${{ github.ref_name }}.zip
        cd ../..
        
        # Create portable package
        cd publish/portable
        Compress-Archive -Path * -DestinationPath ../../BitTicker-portable-${{ github.ref_name }}.zip
        cd ../..
        
    - name: Generate changelog
      id: changelog
      run: |
        echo "## What's Changed in ${{ github.ref_name }}" > CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "### Features" >> CHANGELOG.md
        echo "- Complete cryptocurrency ticker with 12 major exchanges" >> CHANGELOG.md
        echo "- Real-time price monitoring with tooltips" >> CHANGELOG.md
        echo "- Dark theme UI with customizable settings" >> CHANGELOG.md
        echo "- Auto-scrolling ticker with manual override" >> CHANGELOG.md
        echo "- Comprehensive logging and debugging" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "### Supported Exchanges" >> CHANGELOG.md
        echo "- CoinMarketCap, Binance, Bitfinex, Bitstamp, ByBit" >> CHANGELOG.md
        echo "- Coinbase, Crypto.com, Gate.io, Huobi, Kraken, KuCoin, OKX" >> CHANGELOG.md
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: BitTicker ${{ github.ref_name }}
        body_path: CHANGELOG.md
        files: |
          BitTicker-win-x64-${{ github.ref_name }}.zip
          BitTicker-portable-${{ github.ref_name }}.zip
        draft: false
        prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'rc') }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: BitTicker-builds
        path: |
          BitTicker-*.zip
          CHANGELOG.md
